language: ruby
rvm:
  - 1.9.3
  - 2.0.0
before_script:
  cd spec/dummy && rake db:test:load && cd ../..
gemfile:
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile