language: ruby
rvm:
  - 2.5.1
before_install:
  - gem update --system
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
before_script:
  cd spec/dummy && bundle exec rake db:test:load && cd ../..
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails52.gemfile
notifications:
  email:
    - dev@blake.com.au
