language: ruby
rvm:
  - 2.1.5
before_install:
  - gem install bundler
before_script:
  cd spec/dummy && rake db:test:load && cd ../..
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails52.gemfile
notifications:
  email:
    - dev@blake.com.au
