language: ruby
rvm:
  - 2.1.8
before_script:
  cd spec/dummy && rake db:test:load && cd ../..
gemfile:
  - gemfiles/rails40.gemfile
  - gemfiles/rails42.gemfile
notifications:
  email:
    - brad@lucky-dip.net