language: ruby
rvm:
  - 2.0.0
  - 2.1.2
before_install:
  - gem install bundler
before_script:
  cd spec/dummy && rake db:test:load && cd ../..
gemfile:
  - gemfiles/rails40.gemfile
  - gemfiles/rails4013.gemfile
notifications:
  email:
    - brad@lucky-dip.net
