# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 19bbb6fb5e25fc36176e675d05a2d0fee946b96f36abbc187719c636f08539ab5e2d4fe42fc2db82abde5bca76cf09c541b109f64f570d7ccecd75cd886addf1

test:
  secret_key_base: 9e995c0db8c37487a5a018296136dd3b0c616b55714a792c46660bf0ba0faba8fed39d6b99dce939d0e29e989f67241eefcb05f53b90c36aa7983fc8e7712fda

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
